services:
  mongo:
    ports:
      - 127.0.0.1:27017:27017
    container_name: mongo1
    networks:
      - mongo-network
    image: mongo:latest
    command: 'mongod --replSet myReplicaSet --bind_ip_all'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --eval 'try { rs.status() } catch (err) { rs.initiate() }' || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
